var AppConstant = {
    M_SERVER_ERROR: '服务器连接已断开，请重新打开页面后重试。',
    M_NO_SELECT_ROW: '请选择要操作的数据！',
    M_NO_SELECT_TREE: '请选择一个分类！',
    M_CAN_NOT_SELECT_ROOT_TREE: '不能操作根分类！',
    M_CONFIRM_DELETE: '删除后无法恢复，确认要删除？',
    M_CONFIRM_SUBMIT: '提交后将审核，确认提交？',
    M_CONFIRM_SYNC: '选中的记录将生成KIS凭证，确认同步？',
    M_CONFIRM_SYNC2: '选中的记录将生成KIS销售出库单，确认同步？',
    M_CONFIRM_REDCLASH: '确认红冲？',
    M_IS_SAVED: '已保存',
    M_NO_SAVED: '请先保存！',
    M_INFO: '系统提示',
    M_REQUIRED: '不能为空',
    M_MULT_BANK_ACCOUNT: '现金银行多账户',
    M_AUTO_NUMBER: '自动编号',
    RMB: '¥',
    ENTRY_DEFAULT_COUNT: 100,
    UUID_LENGTH: 19,
    MAX_DOUBLE: 999999999999,
    MIN_DOUBLE: - 999999999999
};
